Added support for transparent auth_proxy communication
contiv/contivmodel pull request #64
Opened 2017-04-11 22:32 UTC by dseevr

These are the changes from https://github.com/contiv/modelgen/pull/24.  Regular commit message follows:

This commit does not break any existing functionality for regular netmaster communication

Changes:

- a custom `http.Client` is initialized and used rather than `http.DefaultClient` (this allows us to disable strict cert checking)
- `httpGet`, `httpPost`, and `httpDelete` are modified to use the custom client
- if the user has previously logged into Contiv UI via `netctl login` and is sending a request to a secure netmaster (i.e., `auth_proxy`), we append a `X-Auth-Token` request header with their saved token

Signed-off-by: Bill Robinson <dseevr@users.noreply.github.com>

2017-04-12 00:45 UTC, yuva29 commented on client/contivModelClient.go
> +	if err := addAuthTokenHeader(req); err != nil {
Are we enforcing that all the requests should go through proxy? What if the user wants to bypass proxy and make a call to netmaster directly?

2017-04-12 00:54 UTC, dseevr commented on client/contivModelClient.go
> +	if err := addAuthTokenHeader(req); err != nil {
See line 95.  Non-HTTPS requests return early and don't get the header added (for security reasons)

2017-04-12 00:59 UTC, yuva29 commented on client/contivModelClient.go
> +	if err := addAuthTokenHeader(req); err != nil {
Got it.

2017-04-12 17:25 UTC, rhim approved these changes
LGTM.

2017-04-12 17:28 UTC, jojimt requested changes

2017-04-12 17:28 UTC, jojimt commented on client/contivModelClient.go
> +}
Let's separate out the netctl specific items and move them out of the model as discussed in the modelgen PR.

2017-05-04 00:23 UTC, rhim reviewed
why are there changes for check package in this patch?

2017-05-04 17:20 UTC, dseevr commented
@rhim that was from bringing in contiv's fork of gocheck.  I broke that out into a separate commit

2017-05-04 23:14 UTC, rhim approved these changes
These changes look fine. I am a bit unclear on tests that we need for auth_proxy - basically test that ensures that no command can be run without token.

Another test would be that of invalid/expired token. 

As long as we have those scenarios covered, I think this is good to go.

Please also open the doc change PR for this change.

2017-05-05 00:29 UTC, dseevr commented
@rhim there's no problem with netctl sending requests to auth_proxy without a token (e.g., if they haven't logged in yet or deleted the config after logging in) because they will get back a 401 unauthorized.  auth_proxy has tests to cover that scenario.  It also has tests to cover invalid and expired tokens.

Do you want netctl to refuse to send the requests if the target is https and no token (i.e., config) is present?

2017-05-05 05:19 UTC, rhim commented
No, that’s ok. Shouldn’t overburden client if server side mechanism already exists.

- Himanshu
     .:|:.:|:.

On May 4, 2017, at 5:29 PM, Bill Robinson <notifications@github.com<mailto:notifications@github.com>> wrote:


@rhim<https://github.com/rhim> there's no problem with netctl sending requests to auth_proxy without a token (e.g., if they haven't logged in yet or deleted the config after logging in) because they will get back a 401 unauthorized. auth_proxy has tests to cover that scenario. It also has tests to cover invalid and expired tokens.

Do you want netctl to refuse to send the requests if the target is https and no token (i.e., config) is present?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/contiv/contivmodel/pull/64#issuecomment-299344759>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AMiMKYjK_Iyb4MHEI-QDl7IX-YwkVecpks5r2m1ZgaJpZM4M6uy9>.

2017-05-09 22:46 UTC, merged